# Generated by Django 4.0.4 on 2022-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0004_address_amenity_listing_review_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
