# Generated by Django 4.0.4 on 2022-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0006_alter_listing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
