# Generated by Django 4.0.4 on 2022-05-04 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0007_amenity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='location_lat',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(-90, message='Latitude must be between -90 and 90'), django.core.validators.MaxValueValidator(90, message='Latitude must be between -90 and 90')]),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_lng',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-180, message='Longitiude must be between -180 and 180'), django.core.validators.MaxValueValidator(180, message='Longitiude must be between -180 and 180')]),
        ),
    ]
