# Generated by Django 4.0.4 on 2022-05-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0009_alter_listing_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
