# Generated by Django 4.0.4 on 2022-05-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0010_listing_description'),
        ('roam_app', '0011_alter_listing_location_lat_and_more'),
    ]

    operations = [
    ]
