# Generated by Django 4.0.4 on 2022-05-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0013_remove_listing_rating_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
