# Generated by Django 4.0.4 on 2022-05-05 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0014_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_persons',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
