# Generated by Django 4.0.4 on 2022-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0015_reservation_num_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
