# Generated by Django 4.0.4 on 2022-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0016_listing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='near_park',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
