# Generated by Django 4.0.4 on 2022-05-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roam_app', '0018_alter_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to='listing_images'),
            preserve_default=False,
        ),
    ]
